# site settings
title: Bloggidy Blog to the B-L-O-G
subtitle: A Moderately OK Datascience Blog
email: williamcottrell72@gmail.com
description: Some thoughts about datascience, physics and life.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Da' Street
city: Straight Outta Palo Alto
state: CA
zip_code: 94306
country: United States of America
phone: (650) 898 5362

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
# 500px_url:
facebook_url: https://www.facebook.com/william.cottrell1
github_url: https://github.com/williamcottrell72
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/william-cottrell/
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
